training:
  batch_size: 4
  nms_threshold: 0.1
  score_threshold: 0.96
  pos_threshold: 0.6
  neg_threshold: 0.45
  class_list: ['Car']
  anchor:
    - w: 1.6
      l: 3.9
      h: 1.56
      yaw: 0.
    - w: 1.6
      l: 3.9
      h: 1.56
      yaw: 90.
pointcloud:
  range:
    x: [0., 70.4]
    y: [-40., 40.]
    z: [-3., 1.]
  voxel:
    size:
      x: 0.2
      y: 0.2
      z: 0.4
    point_num: 35